"""empty message

Revision ID: 96aa8047e964
Revises: dd51c1db326a
Create Date: 2021-10-09 14:10:48.734182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbf9d86dce9'
down_revision = 'dd51c1db326a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('createdAt', sa.DateTime(), nullable=False))
    op.add_column('notes', sa.Column('updatedAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'updatedAt')
    op.drop_column('notes', 'createdAt')
    # ### end Alembic commands ###
